import { WebGLConstant } from "./WebGLConstant.js";

/** Bind targets for buffers. */
export enum BufferTarget {
	ARRAY_BUFFER = WebGLConstant.ARRAY_BUFFER,
	ELEMENT_ARRAY_BUFFER = WebGLConstant.ELEMENT_ARRAY_BUFFER,
	COPY_READ_BUFFER = WebGLConstant.COPY_READ_BUFFER,
	COPY_WRITE_BUFFER = WebGLConstant.COPY_WRITE_BUFFER,
	TRANSFORM_FEEDBACK_BUFFER = WebGLConstant.TRANSFORM_FEEDBACK_BUFFER,
	UNIFORM_BUFFER = WebGLConstant.UNIFORM_BUFFER,
	PIXEL_PACK_BUFFER = WebGLConstant.PIXEL_PACK_BUFFER,
	PIXEL_UNPACK_BUFFER = WebGLConstant.PIXEL_UNPACK_BUFFER
}