import { WebGLConstant } from "../index.js";

/** Data types for texel data in textures. */
export enum TextureDataType {
	UNSIGNED_BYTE = WebGLConstant.UNSIGNED_BYTE,
	UNSIGNED_SHORT_5_6_5 = WebGLConstant.UNSIGNED_SHORT_5_6_5,
	UNSIGNED_SHORT_4_4_4_4 = WebGLConstant.UNSIGNED_SHORT_4_4_4_4,
	UNSIGNED_SHORT_5_5_5_1 = WebGLConstant.UNSIGNED_SHORT_5_5_5_1,
	UNSIGNED_SHORT = WebGLConstant.UNSIGNED_SHORT,
	UNSIGNED_INT = WebGLConstant.UNSIGNED_INT,
	UNSIGNED_INT_24_8_WEBGL = WebGLConstant.UNSIGNED_INT_24_8_WEBGL,
	FLOAT = WebGLConstant.FLOAT,
	HALF_FLOAT_OES = WebGLConstant.HALF_FLOAT_OES,
	BYTE = WebGLConstant.BYTE,
	SHORT = WebGLConstant.SHORT,
	INT = WebGLConstant.INT,
	HALF_FLOAT = WebGLConstant.HALF_FLOAT,
	UNSIGNED_INT_2_10_10_10_REV = WebGLConstant.UNSIGNED_INT_2_10_10_10_REV,
	UNSIGNED_INT_10F_11F_11F_REV = WebGLConstant.UNSIGNED_INT_10F_11F_11F_REV,
	UNSIGNED_INT_5_9_9_9_REV = WebGLConstant.UNSIGNED_INT_5_9_9_9_REV,
	UNSIGNED_INT_24_8 = WebGLConstant.UNSIGNED_INT_24_8,
	FLOAT_32_UNSIGNED_INT_24_8_REV = WebGLConstant.FLOAT_32_UNSIGNED_INT_24_8_REV
}