import { WebGLConstant } from "../index.js";

/** Filters for textures. */
export enum TextureFilter {
	LINEAR = WebGLConstant.LINEAR,
	NEAREST = WebGLConstant.NEAREST,
	NEAREST_MIPMAP_NEAREST = WebGLConstant.NEAREST_MIPMAP_NEAREST,
	LINEAR_MIPMAP_NEAREST = WebGLConstant.LINEAR_MIPMAP_NEAREST,
	NEAREST_MIPMAP_LINEAR = WebGLConstant.NEAREST_MIPMAP_LINEAR,
	LINEAR_MIPMAP_LINEAR = WebGLConstant.LINEAR_MIPMAP_LINEAR
}