import { WebGLConstant } from "./WebGLConstant.js";

/** Bind targets for textures. */
export enum TextureTarget {
	TEXTURE_2D = WebGLConstant.TEXTURE_2D,
	TEXTURE_CUBE_MAP = WebGLConstant.TEXTURE_CUBE_MAP,
	TEXTURE_3D = WebGLConstant.TEXTURE_3D,
	TEXTURE_2D_ARRAY = WebGLConstant.TEXTURE_2D_ARRAY,
	TEXTURE_CUBE_MAP_POSITIVE_X = WebGLConstant.TEXTURE_CUBE_MAP_POSITIVE_X,
	TEXTURE_CUBE_MAP_NEGATIVE_X = WebGLConstant.TEXTURE_CUBE_MAP_NEGATIVE_X,
	TEXTURE_CUBE_MAP_POSITIVE_Y = WebGLConstant.TEXTURE_CUBE_MAP_POSITIVE_Y,
	TEXTURE_CUBE_MAP_NEGATIVE_Y = WebGLConstant.TEXTURE_CUBE_MAP_NEGATIVE_Y,
	TEXTURE_CUBE_MAP_POSITIVE_Z = WebGLConstant.TEXTURE_CUBE_MAP_POSITIVE_Z,
	TEXTURE_CUBE_MAP_NEGATIVE_Z = WebGLConstant.TEXTURE_CUBE_MAP_NEGATIVE_Z,
}