# .readthedocs.yml 
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 1

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

python:
  version: 3.8.5
  install:
    - requirements: docs/requirements.txt