import TextureDataFormat from "../../constants/TextureDataFormat.js";
import TextureFormat from "../../constants/TextureFormat.js";

/**
 * Get the corresponding texture format for an internal texture format.
 * @param internalFormat - The internal format.
 * @returns The texture format.
 * @internal
 */
export default function getTextureDataFormatForTextureFormat(
	internalFormat: TextureFormat
) {
	switch (internalFormat) {
		case TextureFormat.RGB:
		case TextureFormat.RGB8:
		case TextureFormat.SRGB8:
		case TextureFormat.RGB565:
		case TextureFormat.RGB8_SNORM:
		case TextureFormat.R11F_G11F_B10F:
		case TextureFormat.RGB9_E5:
		case TextureFormat.RGB16F:
		case TextureFormat.RGB32F:
			return TextureDataFormat.RGB;
		case TextureFormat.RGBA:
		case TextureFormat.RGBA8:
		case TextureFormat.SRGB8_ALPHA8:
		case TextureFormat.RGBA8_SNORM:
		case TextureFormat.RGB5_A1:
		case TextureFormat.RGBA4:
		case TextureFormat.RGB10_A2:
		case TextureFormat.RGBA16F:
		case TextureFormat.RGBA32F:
			return TextureDataFormat.RGBA;
		case TextureFormat.LUMINANCE_ALPHA:
			return TextureDataFormat.LUMINANCE_ALPHA;
		case TextureFormat.LUMINANCE:
			return TextureDataFormat.LUMINANCE;
		case TextureFormat.ALPHA:
			return TextureDataFormat.ALPHA;
		case TextureFormat.SRGB:
			return TextureDataFormat.SRGB;
		case TextureFormat.SRGB_ALPHA:
			return TextureDataFormat.SRGB_ALPHA;
		case TextureFormat.R8:
		case TextureFormat.R8_SNORM:
		case TextureFormat.R16F:
		case TextureFormat.R32F:
			return TextureDataFormat.RED;
		case TextureFormat.R8UI:
		case TextureFormat.R8I:
		case TextureFormat.R16UI:
		case TextureFormat.R16I:
		case TextureFormat.R32UI:
		case TextureFormat.R32I:
			return TextureDataFormat.RED_INTEGER;
		case TextureFormat.RG8:
		case TextureFormat.RG8_SNORM:
		case TextureFormat.RG16F:
		case TextureFormat.RG32F:
			return TextureDataFormat.RG;
		case TextureFormat.RG8UI:
		case TextureFormat.RG8I:
		case TextureFormat.RG16UI:
		case TextureFormat.RG16I:
		case TextureFormat.RG32UI:
		case TextureFormat.RG32I:
			return TextureDataFormat.RG_INTEGER;
		case TextureFormat.RGB8UI:
		case TextureFormat.RGB8I:
		case TextureFormat.RGB16UI:
		case TextureFormat.RGB16I:
		case TextureFormat.RGB32UI:
		case TextureFormat.RGB32I:
			return TextureDataFormat.RGB_INTEGER;
		case TextureFormat.RGBA8UI:
		case TextureFormat.RGBA8I:
		case TextureFormat.RGB10_A2UI:
		case TextureFormat.RGBA16UI:
		case TextureFormat.RGBA16I:
		case TextureFormat.RGBA32UI:
		case TextureFormat.RGBA32I:
			return TextureDataFormat.RGBA_INTEGER;
		case TextureFormat.DEPTH_COMPONENT16:
		case TextureFormat.DEPTH_COMPONENT24:
		case TextureFormat.DEPTH_COMPONENT32F:
			return TextureDataFormat.DEPTH_COMPONENT;
		case TextureFormat.DEPTH24_STENCIL8:
		case TextureFormat.DEPTH32F_STENCIL8:
			return TextureDataFormat.DEPTH_STENCIL;
		case TextureFormat.COMPRESSED_R11_EAC:
			return TextureDataFormat.COMPRESSED_R11_EAC;
		case TextureFormat.COMPRESSED_SIGNED_R11_EAC:
			return TextureDataFormat.COMPRESSED_SIGNED_R11_EAC;
		case TextureFormat.COMPRESSED_RG11_EAC:
			return TextureDataFormat.COMPRESSED_RG11_EAC;
		case TextureFormat.COMPRESSED_SIGNED_RG11_EAC:
			return TextureDataFormat.COMPRESSED_SIGNED_RG11_EAC;
		case TextureFormat.COMPRESSED_RGB8_ETC2:
			return TextureDataFormat.COMPRESSED_RGB8_ETC2;
		case TextureFormat.COMPRESSED_RGBA8_ETC2_EAC:
			return TextureDataFormat.COMPRESSED_RGBA8_ETC2_EAC;
		case TextureFormat.COMPRESSED_SRGB8_ETC2:
			return TextureDataFormat.COMPRESSED_SRGB8_ETC2;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ETC2_EAC:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ETC2_EAC;
		case TextureFormat.COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2:
			return TextureDataFormat.COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2;
		case TextureFormat.COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2:
			return TextureDataFormat.COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2;
		case TextureFormat.COMPRESSED_RGB_S3TC_DXT1_EXT:
			return TextureDataFormat.COMPRESSED_RGB_S3TC_DXT1_EXT;
		case TextureFormat.COMPRESSED_RGBA_S3TC_DXT1_EXT:
			return TextureDataFormat.COMPRESSED_RGBA_S3TC_DXT1_EXT;
		case TextureFormat.COMPRESSED_RGBA_S3TC_DXT3_EXT:
			return TextureDataFormat.COMPRESSED_RGBA_S3TC_DXT3_EXT;
		case TextureFormat.COMPRESSED_RGBA_S3TC_DXT5_EXT:
			return TextureDataFormat.COMPRESSED_RGBA_S3TC_DXT5_EXT;
		case TextureFormat.COMPRESSED_SRGB_S3TC_DXT1_EXT:
			return TextureDataFormat.COMPRESSED_SRGB_S3TC_DXT1_EXT;
		case TextureFormat.COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT:
			return TextureDataFormat.COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT;
		case TextureFormat.COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT:
			return TextureDataFormat.COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT;
		case TextureFormat.COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT:
			return TextureDataFormat.COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT;
		case TextureFormat.COMPRESSED_RGB_PVRTC_4BPPV1_IMG:
			return TextureDataFormat.COMPRESSED_RGB_PVRTC_4BPPV1_IMG;
		case TextureFormat.COMPRESSED_RGBA_PVRTC_4BPPV1_IMG:
			return TextureDataFormat.COMPRESSED_RGBA_PVRTC_4BPPV1_IMG;
		case TextureFormat.COMPRESSED_RGB_PVRTC_2BPPV1_IMG:
			return TextureDataFormat.COMPRESSED_RGB_PVRTC_2BPPV1_IMG;
		case TextureFormat.COMPRESSED_RGBA_PVRTC_2BPPV1_IMG:
			return TextureDataFormat.COMPRESSED_RGBA_PVRTC_2BPPV1_IMG;
		case TextureFormat.COMPRESSED_RGBA_ASTC_4x4_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_4x4_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_5x4_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_5x4_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_5x5_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_5x5_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_6x5_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_6x5_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_6x6_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_6x6_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_8x5_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_8x5_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_8x6_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_8x6_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_8x8_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_8x8_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_10x5_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_10x5_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_10x6_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_10x6_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_10x8_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_10x8_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_10x10_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_10x10_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_12x10_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_12x10_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR;
		case TextureFormat.COMPRESSED_RGBA_ASTC_12x12_KHR:
			return TextureDataFormat.COMPRESSED_RGBA_ASTC_12x12_KHR;
		case TextureFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR:
			return TextureDataFormat.COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR;
		case TextureFormat.COMPRESSED_RGBA_BPTC_UNORM_EXT:
			return TextureDataFormat.COMPRESSED_RGBA_BPTC_UNORM_EXT;
		case TextureFormat.COMPRESSED_SRGB_ALPHA_BPTC_UNORM_EXT:
			return TextureDataFormat.COMPRESSED_SRGB_ALPHA_BPTC_UNORM_EXT;
		case TextureFormat.COMPRESSED_RGB_BPTC_SIGNED_FLOAT_EXT:
			return TextureDataFormat.COMPRESSED_RGB_BPTC_SIGNED_FLOAT_EXT;
		case TextureFormat.COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT_EXT:
			return TextureDataFormat.COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT_EXT;
		case TextureFormat.COMPRESSED_RED_RGTC1_EXT:
			return TextureDataFormat.COMPRESSED_RED_RGTC1_EXT;
		case TextureFormat.COMPRESSED_SIGNED_RED_RGTC1_EXT:
			return TextureDataFormat.COMPRESSED_SIGNED_RED_RGTC1_EXT;
		case TextureFormat.COMPRESSED_RED_GREEN_RGTC2_EXT:
			return TextureDataFormat.COMPRESSED_RED_GREEN_RGTC2_EXT;
		case TextureFormat.COMPRESSED_SIGNED_RED_GREEN_RGTC2_EXT:
		default: // Not possible as long as TypeScript is obeyed.
			return TextureDataFormat.COMPRESSED_SIGNED_RED_GREEN_RGTC2_EXT;
	}
}
