export { default as BufferTarget } from "#BufferTarget";
export { default as FramebufferTarget } from "#FramebufferTarget";
export { default as ShaderType } from "#ShaderType";
export { default as TextureTarget } from "#TextureTarget";
export { default as Texture } from "#Texture";
export { default as Buffer } from "#Buffer";
export { default as Context } from "#Context";
export { default as Framebuffer } from "#Framebuffer";
export { default as Program } from "#Program";
export { default as Renderbuffer } from "#Renderbuffer";
export { default as Shader } from "#Shader";
export type { Canvas } from "#Canvas";
export type { default as Color } from "#Color";
export { default as ProgramLinkError } from "#ProgramLinkError";
export { default as ShaderCompileError } from "#ShaderCompileError";
export { default as UnsupportedOperationError } from "#UnsupportedOperationError";
