name: Push

on:
  push:
    branches:
      - master

jobs:
  document:
    name: Deploy documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: npm i
      - name: Build documentation
        run: npm run esdoc
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:Lakuna/Umbra-Docs.git
          BRANCH: gh-pages
          FOLDER: docs
          SSH_PRIVATE_KEY: ${{ secrets.DOCUMENTATION_DEPLOY_KEY }}
