name: Test

on:
  pull_request:
    types:
      - opened
      - edited
  push:

jobs:
  test:
    name: Test
    permissions: {}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          [
            "1.x",
            "2.x",
            "3.x",
            "4.x",
            "5.x",
            "6.x",
            "7.x",
            "8.x",
            "9.x",
            "10.x",
            "11.x",
            "12.x",
            "13.x",
            "14.x",
            "15.x",
            "16.x",
            "17.x",
            "18.x",
            "19.x",
            "20.x",
            "21.x",
            "22.x"
          ]
    steps:
      - name: Check-Out Repository
        uses: actions/checkout@v4
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Build Documentation
        run: npm run doc
